/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
      "./pages/**/*.{js,ts,jsx,tsx}",
      "./components/**/*.{js,ts,jsx,tsx}",
      "./public/**/*.{js,ts,jsx,tsx}",
      "./styles/**/*.{css,scss}"
    ],
    theme: {
      extend: {
        colors: {
          gray: {
            700: '#2D3748',
            800: '#1A202C',
            900: '#0F141E',
          },
          slate: {
            300: '#CBD5E1',
            400: '#94A3B8',
            700: '#334155',
            800: '#1E293B',
            900: '#0F172A',
          },
          primary: {
            300: '#7DD3FC',
            400: '#38BDF8',
            500: '#0EA5E9',
            600: '#0284C7',
            700: '#0369A1',
          },
          accent: {
            300: '#C084FC',
            400: '#A855F7',
            500: '#9333EA',
          },
          success: {
            400: '#34D399',
            500: '#10B981',
          },
          emerald: {
            400: '#34D399',
            500: '#10B981',
          },
          rose: {
            400: '#FB7185',
            500: '#F43F5E',
          },
          blue: {
            400: '#60A5FA',
            500: '#3B82F6',
          },
          green: {
            400: '#4ADE80',
            500: '#22C55E',
          },
          red: {
            400: '#F87171',
            500: '#EF4444',
          },
        },
        backgroundImage: {
          'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
          'gradient-tech': 'linear-gradient(to bottom right, rgb(15, 23, 42) 0%, rgb(88, 28, 135) 100%)',
          'gradient-glow': 'radial-gradient(circle at center, var(--tw-gradient-stops))',
          'dot-pattern': "radial-gradient(circle at center, #38BDF8 1px, transparent 1px)",
        },
        animation: {
          'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
          'progress-pulse': 'pulse 2s infinite',
          'shimmer': 'shimmer 3s infinite',
        },
        keyframes: {
          pulse: {
            '0%, 100%': { transform: 'scale(1)', opacity: '1' },
            '50%': { transform: 'scale(1.1)', opacity: '0.8' },
          },
          shimmer: {
            '0%': { backgroundPosition: '-200% 0' },
            '100%': { backgroundPosition: '200% 0' },
          }
        },
        boxShadow: {
          'glow': '0 0 15px rgba(168, 85, 247, 0.15)',
          'glow-lg': '0 0 30px rgba(168, 85, 247, 0.25)',
        },
        fontFamily: {
          sans: ['Inter', 'system-ui', 'sans-serif'],
          mono: ['IBM Plex Mono', 'monospace'],
          display: ['Space Grotesk', 'system-ui', 'sans-serif'],
          tech: ['Chakra Petch', 'system-ui', 'sans-serif'],
        },
        spacing: {
          '0.5': '0.125rem',      // 2px
          '1.5': '0.375rem',      // 6px
          '2.5': '0.625rem',      // 10px
          '18': '4.5rem',
          '22': '5.5rem',
          '72': '18rem',
          '84': '21rem',
          '96': '24rem',
        },
        backdropBlur: {
          'xs': '2px',
        },
        borderRadius: {
          'xl': '0.75rem',
          '2xl': '1rem',
          '3xl': '1.5rem',
        },
        transitionDuration: {
          '2000': '2000ms',
          '3000': '3000ms',
        },
        transitionTimingFunction: {
          'bounce-in': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
        },
        scale: {
          '102': '1.02',
          '105': '1.05',
        },
        zIndex: {
          '60': '60',
          '70': '70',
          '80': '80',
          '90': '90',
          '100': '100',
        },
        extend: {
          '.nav-container': {
            background: 'rgba(10, 15, 26, 0.95)',
            backdropFilter: 'blur(20px)',
            borderBottom: '1px solid rgba(56, 189, 248, 0.15)',
            boxShadow: '0 4px 20px rgba(0, 0, 0, 0.2)',
            position: 'fixed',
            top: '0',
            left: '0',
            right: '0',
            zIndex: '50',
            padding: '0.5rem 0',
            transition: 'all 0.3s ease',
          },
          '.nav-content': {
            maxWidth: '80rem',
            margin: '0 auto',
            padding: '0 1.5rem',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            height: '3rem',
          },
          '.nav-brand': {
            fontSize: '1.25rem',
            fontWeight: '700',
            letterSpacing: '-0.025em',
            background: 'linear-gradient(135deg, #60A5FA 0%, #A855F7 100%)',
            WebkitBackgroundClip: 'text',
            backgroundClip: 'text',
            color: 'transparent',
            textShadow: '0 0 20px rgba(168, 85, 247, 0.25)',
            display: 'flex',
            alignItems: 'center',
            gap: '0.5rem',
            transition: 'all 0.3s ease',
            padding: '0.25rem 0.5rem',
            borderRadius: '0.375rem',
          },
          '.nav-brand:hover': {
            textShadow: '0 0 30px rgba(168, 85, 247, 0.35)',
            transform: 'scale(1.02)',
            background: 'rgba(56, 189, 248, 0.1)',
          },
          '.nav-links': {
            display: 'flex',
            alignItems: 'center',
            gap: '0.25rem',
            background: 'rgba(15, 23, 42, 0.4)',
            padding: '0.25rem',
            borderRadius: '0.5rem',
            border: '1px solid rgba(56, 189, 248, 0.1)',
          },
          '.nav-link': {
            position: 'relative',
            padding: '0.375rem 0.75rem',
            borderRadius: '0.375rem',
            fontSize: '0.875rem',
            fontWeight: '500',
            transition: 'all 0.2s ease',
            color: '#CBD5E1',
            textAlign: 'center',
            whiteSpace: 'nowrap',
            letterSpacing: '-0.01em',
          },
          '.nav-link:hover': {
            background: 'rgba(56, 189, 248, 0.1)',
            color: '#E2E8F0',
            transform: 'translateY(-1px)',
          },
          '.nav-link.active': {
            color: '#38BDF8',
            background: 'rgba(56, 189, 248, 0.15)',
            fontWeight: '600',
          },
          '.nav-link.active::after': {
            content: "''",
            position: 'absolute',
            bottom: '-1px',
            left: '50%',
            transform: 'translateX(-50%)',
            width: '24px',
            height: '2px',
            background: 'linear-gradient(to right, #38BDF8, #A855F7)',
            borderRadius: '1px',
          },
          '.nav-button': {
            background: 'linear-gradient(135deg, rgba(96, 165, 250, 0.2) 0%, rgba(168, 85, 247, 0.2) 100%)',
            border: '1px solid rgba(168, 85, 247, 0.3)',
            color: '#E2E8F0',
            padding: '0.375rem 1rem',
            borderRadius: '0.375rem',
            fontSize: '0.875rem',
            fontWeight: '600',
            letterSpacing: '0.01em',
            transition: 'all 0.2s ease',
            display: 'inline-flex',
            alignItems: 'center',
            justifyContent: 'center',
            cursor: 'pointer',
            position: 'relative',
            overflow: 'hidden',
            zIndex: '1',
            textAlign: 'center',
            boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
          },
          '.nav-button:hover': {
            background: 'linear-gradient(135deg, rgba(96, 165, 250, 0.3) 0%, rgba(168, 85, 247, 0.3) 100%)',
            borderColor: 'rgba(168, 85, 247, 0.5)',
            color: '#F3F4F6',
            transform: 'translateY(-1px)',
            boxShadow: '0 4px 12px rgba(168, 85, 247, 0.2)',
          },
          '.nav-button:active': {
            transform: 'translateY(0)',
            boxShadow: '0 2px 6px rgba(168, 85, 247, 0.15)',
          },
          '.hero-gradient': {
            background: 'linear-gradient(135deg, rgba(15, 23, 42, 0.8) 0%, rgba(30, 41, 59, 0.8) 100%)',
            backdropFilter: 'blur(20px)',
            border: '1px solid rgba(56, 189, 248, 0.15)',
            borderRadius: '1rem',
            padding: '2rem',
            boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
            position: 'relative',
            overflow: 'hidden',
          },
          '.hero-gradient::before': {
            content: "''",
            position: 'absolute',
            top: '0',
            left: '0',
            right: '0',
            height: '1px',
            background: 'linear-gradient(90deg, transparent, rgba(56, 189, 248, 0.3), transparent)',
          },
          '.hero-gradient::after': {
            content: "''",
            position: 'absolute',
            bottom: '0',
            left: '0',
            right: '0',
            height: '1px',
            background: 'linear-gradient(90deg, transparent, rgba(56, 189, 248, 0.3), transparent)',
          },
          '.prometheus-title': {
            fontFamily: 'Space Grotesk, system-ui, sans-serif',
            fontSize: '3rem',
            lineHeight: '1.15',
            letterSpacing: '-0.04em',
            fontWeight: '800',
            textShadow: '0 0 30px rgba(168, 85, 247, 0.25)',
            marginBottom: '1.5rem',
            textAlign: 'center',
            display: 'block',
            width: '100%',
            background: 'linear-gradient(135deg, #60A5FA 0%, #A855F7 50%, #C084FC 100%)',
            WebkitBackgroundClip: 'text',
            backgroundClip: 'text',
            color: 'transparent',
            padding: '0.5rem 0',
          },
          '.subtitle-box': {
            background: 'rgba(15, 23, 42, 0.6)',
            border: '1px solid rgba(56, 189, 248, 0.15)',
            borderRadius: '0.5rem',
            padding: '1.25rem',
            margin: '0 auto 2rem',
            maxWidth: '42rem',
            boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
            transition: 'all 0.3s ease',
            position: 'relative',
            overflow: 'hidden',
          },
          '.subtitle-box::before': {
            content: "''",
            position: 'absolute',
            top: '0',
            left: '0',
            width: '100%',
            height: '2px',
            background: 'linear-gradient(90deg, transparent, rgba(56, 189, 248, 0.3), transparent)',
          },
          '.subtitle-box:hover': {
            background: 'rgba(15, 23, 42, 0.7)',
            borderColor: 'rgba(56, 189, 248, 0.3)',
            transform: 'translateY(-2px)',
            boxShadow: '0 6px 16px rgba(0, 0, 0, 0.1), 0 0 12px rgba(56, 189, 248, 0.15)',
          },
          '.section-title': {
            fontFamily: 'Space Grotesk, system-ui, sans-serif',
            fontSize: '2.25rem',
            lineHeight: '1.2',
            letterSpacing: '-0.03em',
            fontWeight: '700',
            textAlign: 'center',
            display: 'block',
            width: '100%',
            marginBottom: '1rem',
            background: 'linear-gradient(135deg, #60A5FA 0%, #A855F7 100%)',
            WebkitBackgroundClip: 'text',
            backgroundClip: 'text',
            color: 'transparent',
          },
          '.section-subtitle': {
            fontFamily: 'Inter, system-ui, sans-serif',
            fontSize: '1.125rem',
            lineHeight: '1.5',
            letterSpacing: '-0.01em',
            fontWeight: '400',
            textAlign: 'center',
            display: 'block',
            width: '100%',
            color: '#94A3B8',
          },
          '.feature-card': {
            background: 'rgba(15, 23, 42, 0.6)',
            border: '1px solid rgba(56, 189, 248, 0.15)',
            borderRadius: '0.5rem',
            padding: '1.25rem',
            transition: 'all 0.3s ease',
            height: '100%',
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            overflow: 'hidden',
            maxWidth: '320px',
            margin: '0 auto',
            boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
          },
          '.feature-card::before': {
            content: "''",
            position: 'absolute',
            top: '0',
            left: '0',
            width: '100%',
            height: '2px',
            background: 'linear-gradient(90deg, transparent, rgba(56, 189, 248, 0.3), transparent)',
          },
          '.feature-card:hover': {
            background: 'rgba(15, 23, 42, 0.7)',
            borderColor: 'rgba(56, 189, 248, 0.3)',
            transform: 'translateY(-2px)',
            boxShadow: '0 6px 16px rgba(0, 0, 0, 0.1), 0 0 12px rgba(56, 189, 248, 0.15)',
          },
          '.feature-card .icon-container': {
            width: '32px',
            height: '32px',
            borderRadius: '8px',
            background: 'rgba(56, 189, 248, 0.1)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto 0.75rem',
            transition: 'all 0.3s ease',
          },
          '.feature-card:hover .icon-container': {
            background: 'rgba(56, 189, 248, 0.2)',
            transform: 'scale(1.1)',
          },
          '.card-title': {
            fontFamily: 'Space Grotesk, system-ui, sans-serif',
            fontSize: '1.125rem',
            lineHeight: '1.3',
            letterSpacing: '-0.02em',
            fontWeight: '700',
            textAlign: 'center',
            display: 'block',
            width: '100%',
            marginBottom: '0.75rem',
            color: '#E2E8F0',
          },
          '.card-subtitle': {
            fontFamily: 'Inter, system-ui, sans-serif',
            fontSize: '0.875rem',
            lineHeight: '1.5',
            letterSpacing: '-0.01em',
            fontWeight: '400',
            textAlign: 'center',
            display: 'block',
            width: '100%',
            color: '#94A3B8',
          },
          '.step-card': {
            background: 'rgba(15, 23, 42, 0.6)',
            border: '1px solid rgba(56, 189, 248, 0.15)',
            borderRadius: '0.5rem',
            padding: '1.5rem',
            transition: 'all 0.3s ease',
            height: '100%',
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            overflow: 'hidden',
            maxWidth: '320px',
            margin: '0 auto',
            boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
          },
          '.step-card::before': {
            content: "''",
            position: 'absolute',
            top: '0',
            left: '0',
            width: '100%',
            height: '2px',
            background: 'linear-gradient(90deg, transparent, rgba(56, 189, 248, 0.3), transparent)',
          },
          '.step-card:hover': {
            background: 'rgba(15, 23, 42, 0.7)',
            borderColor: 'rgba(56, 189, 248, 0.3)',
            transform: 'translateY(-2px)',
            boxShadow: '0 6px 16px rgba(0, 0, 0, 0.1), 0 0 12px rgba(56, 189, 248, 0.15)',
          },
          '.step-number': {
            fontSize: '2.5rem',
            fontWeight: '800',
            lineHeight: '1',
            marginBottom: '0.75rem',
            background: 'linear-gradient(135deg, #60A5FA 0%, #A855F7 100%)',
            WebkitBackgroundClip: 'text',
            backgroundClip: 'text',
            color: 'transparent',
            opacity: '0.3',
            transition: 'opacity 0.3s ease',
            fontFamily: 'Space Grotesk, system-ui, sans-serif',
            letterSpacing: '-0.04em',
            textAlign: 'center',
          },
          '.step-card:hover .step-number': {
            opacity: '0.5',
          },
          '.gradient-button': {
            background: 'linear-gradient(135deg, rgba(96, 165, 250, 0.2) 0%, rgba(168, 85, 247, 0.2) 100%)',
            border: '1px solid rgba(168, 85, 247, 0.3)',
            color: '#E2E8F0',
            padding: '0.5rem 1.25rem',
            borderRadius: '0.375rem',
            fontSize: '0.875rem',
            fontWeight: '600',
            letterSpacing: '0.01em',
            transition: 'all 0.2s ease',
            display: 'inline-flex',
            alignItems: 'center',
            justifyContent: 'center',
            cursor: 'pointer',
            position: 'relative',
            overflow: 'hidden',
            zIndex: '1',
            textAlign: 'center',
            boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
          },
          '.gradient-button:hover': {
            background: 'linear-gradient(135deg, rgba(96, 165, 250, 0.3) 0%, rgba(168, 85, 247, 0.3) 100%)',
            borderColor: 'rgba(168, 85, 247, 0.5)',
            color: '#F3F4F6',
            transform: 'translateY(-1px)',
            boxShadow: '0 4px 12px rgba(168, 85, 247, 0.2)',
          },
          '.gradient-button:active': {
            transform: 'translateY(0)',
            boxShadow: '0 2px 6px rgba(168, 85, 247, 0.15)',
          },
          '.features-grid': {
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
            gap: '1.5rem',
            width: '100%',
            maxWidth: '1200px',
            margin: '0 auto',
          },
          '.steps-grid': {
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
            gap: '1.5rem',
            width: '100%',
            maxWidth: '1200px',
            margin: '0 auto',
          },
          '.footer': {
            background: 'rgba(10, 15, 26, 0.8)',
            backdropFilter: 'blur(12px)',
            borderTop: '1px solid rgba(56, 189, 248, 0.15)',
            padding: '3rem 0 2rem',
            marginTop: '5rem',
          },
          '.footer-content': {
            maxWidth: '80rem',
            margin: '0 auto',
            padding: '0 1.5rem',
          },
          '.footer-grid': {
            display: 'grid',
            gridTemplateColumns: 'repeat(1, 1fr)',
            gap: '2rem',
            marginBottom: '3rem',
          },
          '.footer-brand': {
            fontFamily: 'Space Grotesk, system-ui, sans-serif',
            fontSize: '1.25rem',
            fontWeight: '700',
            letterSpacing: '-0.02em',
            marginBottom: '1rem',
            background: 'linear-gradient(135deg, #60A5FA 0%, #A855F7 100%)',
            WebkitBackgroundClip: 'text',
            backgroundClip: 'text',
            color: 'transparent',
          },
          '.footer-description': {
            fontSize: '0.875rem',
            lineHeight: '1.5',
            color: '#94A3B8',
            marginBottom: '1.5rem',
          },
          '.footer-heading': {
            fontFamily: 'IBM Plex Mono, monospace',
            fontSize: '0.75rem',
            fontWeight: '600',
            letterSpacing: '0.1em',
            textTransform: 'uppercase',
            color: '#CBD5E1',
            marginBottom: '1rem',
          },
          '.footer-links': {
            display: 'flex',
            flexDirection: 'column',
            gap: '0.5rem',
          },
          '.footer-link': {
            fontSize: '0.875rem',
            color: '#94A3B8',
            transition: 'color 0.2s ease',
            textDecoration: 'none',
          },
          '.footer-link:hover': {
            color: '#C084FC',
          },
          '.footer-bottom': {
            borderTop: '1px solid rgba(56, 189, 248, 0.1)',
            marginTop: '3rem',
            paddingTop: '2rem',
            display: 'flex',
            flexWrap: 'wrap',
            justifyContent: 'space-between',
            alignItems: 'center',
            gap: '1rem',
          },
          '.footer-copyright': {
            fontSize: '0.75rem',
            color: '#64748B',
          },
          '.footer-social': {
            display: 'flex',
            gap: '1.5rem',
          },
          '.footer-social-link': {
            fontSize: '0.75rem',
            color: '#64748B',
            transition: 'color 0.2s ease',
            textDecoration: 'none',
          },
          '.footer-social-link:hover': {
            color: '#C084FC',
          },
          '.hero-text': {
            fontFamily: 'Space Grotesk, system-ui, sans-serif',
            fontSize: '3.5rem',
            lineHeight: '1.15',
            letterSpacing: '-0.04em',
            fontWeight: '800',
            textShadow: '0 0 30px rgba(168, 85, 247, 0.25)',
            marginBottom: '1.5rem',
            textAlign: 'center',
            display: 'block',
            width: '100%',
          },
          '.section-title': {
            fontFamily: 'Space Grotesk, system-ui, sans-serif',
            fontSize: '2.5rem',
            lineHeight: '1.2',
            letterSpacing: '-0.03em',
            fontWeight: '700',
            textAlign: 'center',
            display: 'block',
            width: '100%',
            marginBottom: '1rem',
            background: 'linear-gradient(135deg, #60A5FA 0%, #A855F7 100%)',
            WebkitBackgroundClip: 'text',
            backgroundClip: 'text',
            color: 'transparent',
          },
          '.subtitle-box': {
            background: 'rgba(30, 41, 59, 0.6)',
            border: '1px solid rgba(71, 85, 105, 0.4)',
            borderRadius: '0.5rem',
            padding: '1.25rem',
            margin: '0 auto 2rem',
            maxWidth: '42rem',
            boxShadow: '0 4px 12px rgba(0, 0, 0, 0.1)',
            transition: 'all 0.3s ease',
          },
          '.subtitle-box:hover': {
            background: 'rgba(30, 41, 59, 0.7)',
            borderColor: 'rgba(168, 85, 247, 0.3)',
            transform: 'translateY(-2px)',
            boxShadow: '0 6px 16px rgba(0, 0, 0, 0.1), 0 0 12px rgba(168, 85, 247, 0.15)',
          },
          '.section-subtitle': {
            fontFamily: 'Inter, system-ui, sans-serif',
            fontSize: '1.25rem',
            lineHeight: '1.5',
            letterSpacing: '-0.01em',
            fontWeight: '400',
            textAlign: 'center',
            display: 'block',
            width: '100%',
            color: '#94A3B8',
          },
          '.card-title': {
            fontFamily: 'Space Grotesk, system-ui, sans-serif',
            fontSize: '1.25rem',
            lineHeight: '1.3',
            letterSpacing: '-0.02em',
            fontWeight: '700',
            textAlign: 'center',
            display: 'block',
            width: '100%',
            marginBottom: '0.75rem',
            color: '#E2E8F0',
          },
          '.card-subtitle': {
            fontFamily: 'Inter, system-ui, sans-serif',
            fontSize: '1rem',
            lineHeight: '1.5',
            letterSpacing: '-0.01em',
            fontWeight: '400',
            textAlign: 'center',
            display: 'block',
            width: '100%',
            color: '#94A3B8',
          },
          '.feature-card': {
            background: 'rgba(30, 41, 59, 0.6)',
            border: '1px solid rgba(71, 85, 105, 0.4)',
            borderRadius: '0.5rem',
            padding: '1.25rem',
            transition: 'all 0.3s ease',
            height: '100%',
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            overflow: 'hidden',
            maxWidth: '320px',
            margin: '0 auto',
          },
          '.feature-card:hover': {
            background: 'rgba(30, 41, 59, 0.7)',
            borderColor: 'rgba(168, 85, 247, 0.3)',
            transform: 'translateY(-2px)',
            boxShadow: '0 6px 16px rgba(0, 0, 0, 0.1), 0 0 12px rgba(168, 85, 247, 0.15)',
          },
          '.feature-card .icon-container': {
            width: '32px',
            height: '32px',
            borderRadius: '8px',
            background: 'rgba(168, 85, 247, 0.1)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: '0.75rem',
            transition: 'all 0.3s ease',
          },
          '.feature-card .icon-container span': {
            fontSize: '1rem',
            lineHeight: '1',
          },
          '.feature-card h3': {
            color: '#E2E8F0',
            fontSize: '1.125rem',
            fontWeight: '700',
            marginBottom: '0.5rem',
            fontFamily: 'Space Grotesk, system-ui, sans-serif',
            letterSpacing: '-0.02em',
            lineHeight: '1.3',
          },
          '.feature-card p': {
            color: '#94A3B8',
            fontSize: '0.875rem',
            lineHeight: '1.5',
            fontWeight: '400',
            fontFamily: 'Inter, system-ui, sans-serif',
            letterSpacing: '-0.01em',
          },
          '.step-card': {
            background: 'rgba(30, 41, 59, 0.5)',
            border: '1px solid rgba(71, 85, 105, 0.4)',
            borderRadius: '0.5rem',
            padding: '1.5rem',
            transition: 'all 0.3s ease',
            height: '100%',
            display: 'flex',
            flexDirection: 'column',
            position: 'relative',
            overflow: 'hidden',
            maxWidth: '320px',
            margin: '0 auto',
          },
          '.step-card:hover': {
            background: 'rgba(30, 41, 59, 0.6)',
            borderColor: 'rgba(168, 85, 247, 0.3)',
            transform: 'translateY(-2px)',
            boxShadow: '0 6px 16px rgba(0, 0, 0, 0.1), 0 0 12px rgba(168, 85, 247, 0.1)',
          },
          '.step-card::before': {
            content: "''",
            position: 'absolute',
            top: '0',
            left: '0',
            right: '0',
            height: '2px',
            background: 'linear-gradient(90deg, #60A5FA, #A855F7)',
            opacity: '0',
            transition: 'opacity 0.3s ease',
          },
          '.step-card:hover::before': {
            opacity: '1',
          },
          '.step-card .step-number': {
            fontSize: '2.5rem',
            fontWeight: '800',
            lineHeight: '1',
            marginBottom: '0.75rem',
            background: 'linear-gradient(135deg, #60A5FA 0%, #A855F7 100%)',
            WebkitBackgroundClip: 'text',
            backgroundClip: 'text',
            color: 'transparent',
            opacity: '0.3',
            transition: 'opacity 0.3s ease',
            fontFamily: 'Space Grotesk, system-ui, sans-serif',
            letterSpacing: '-0.04em',
          },
          '.step-card:hover .step-number': {
            opacity: '0.5',
          },
          '.step-card h3': {
            color: '#E2E8F0',
            fontSize: '1.125rem',
            fontWeight: '700',
            marginBottom: '0.5rem',
            fontFamily: 'Space Grotesk, system-ui, sans-serif',
            letterSpacing: '-0.02em',
            lineHeight: '1.3',
          },
          '.step-card p': {
            color: '#94A3B8',
            fontSize: '0.875rem',
            lineHeight: '1.5',
            fontWeight: '400',
            fontFamily: 'Inter, system-ui, sans-serif',
            letterSpacing: '-0.01em',
          },
          'footer': {
            background: 'rgba(15, 23, 42, 0.6)',
            backdropFilter: 'blur(12px)',
            borderTop: '1px solid rgba(71, 85, 105, 0.3)',
            padding: '3rem 0 2rem',
            marginTop: '5rem',
          },
          'footer h3': {
            fontFamily: 'Space Grotesk, system-ui, sans-serif',
            fontSize: '1.25rem',
            fontWeight: '700',
            letterSpacing: '-0.02em',
            marginBottom: '1rem',
          },
          'footer h4': {
            fontFamily: 'IBM Plex Mono, monospace',
            fontSize: '0.75rem',
            fontWeight: '600',
            letterSpacing: '0.1em',
            textTransform: 'uppercase',
            color: '#CBD5E1',
            marginBottom: '1rem',
          },
          'footer p': {
            fontSize: '0.875rem',
            lineHeight: '1.5',
            color: '#94A3B8',
          },
          'footer .social-links': {
            display: 'flex',
            gap: '1rem',
            marginTop: '1.5rem',
          },
          'footer .social-links a': {
            color: '#94A3B8',
            transition: 'color 0.2s ease',
          },
          'footer .social-links a:hover': {
            color: '#C084FC',
          },
          'footer ul': {
            margin: '0',
            padding: '0',
            listStyle: 'none',
          },
          'footer ul li': {
            marginBottom: '0.5rem',
          },
          'footer ul li a': {
            fontSize: '0.875rem',
            color: '#94A3B8',
            transition: 'color 0.2s ease',
            display: 'inline-block',
          },
          'footer ul li a:hover': {
            color: '#C084FC',
          },
          '.footer-bottom': {
            borderTop: '1px solid rgba(71, 85, 105, 0.3)',
            marginTop: '3rem',
            paddingTop: '2rem',
            display: 'flex',
            flexWrap: 'wrap',
            justifyContent: 'space-between',
            alignItems: 'center',
            gap: '1rem',
          },
          '.footer-bottom p': {
            fontSize: '0.75rem',
            color: '#64748B',
          },
          '.footer-bottom .links': {
            display: 'flex',
            gap: '1.5rem',
          },
          '.footer-bottom .links a': {
            fontSize: '0.75rem',
            color: '#64748B',
            transition: 'color 0.2s ease',
          },
          '.footer-bottom .links a:hover': {
            color: '#C084FC',
          },
          '.nav-container': {
            background: 'rgba(15, 23, 42, 0.9)',
            backdropFilter: 'blur(20px)',
            borderBottom: '1px solid rgba(71, 85, 105, 0.4)',
            boxShadow: '0 4px 20px rgba(0, 0, 0, 0.15)',
            position: 'fixed',
            top: '0',
            left: '0',
            right: '0',
            zIndex: '50',
            padding: '0.75rem 0',
            transition: 'all 0.3s ease',
          },
          '.nav-content': {
            maxWidth: '80rem',
            margin: '0 auto',
            padding: '0 1rem',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            height: '3.5rem',
          },
          '.nav-brand': {
            fontSize: '1.5rem',
            fontWeight: '700',
            letterSpacing: '-0.025em',
            background: 'linear-gradient(135deg, #60A5FA 0%, #A855F7 100%)',
            WebkitBackgroundClip: 'text',
            backgroundClip: 'text',
            color: 'transparent',
            textShadow: '0 0 20px rgba(168, 85, 247, 0.25)',
            display: 'flex',
            alignItems: 'center',
            gap: '0.5rem',
            transition: 'all 0.3s ease',
          },
          '.nav-brand:hover': {
            textShadow: '0 0 30px rgba(168, 85, 247, 0.35)',
            transform: 'scale(1.02)',
          },
          '.nav-links': {
            display: 'flex',
            alignItems: 'center',
            gap: '0.5rem',
            background: 'rgba(15, 23, 42, 0.4)',
            padding: '0.25rem',
            borderRadius: '0.5rem',
            border: '1px solid rgba(71, 85, 105, 0.2)',
          },
          '.nav-link': {
            position: 'relative',
            padding: '0.5rem 0.875rem',
            borderRadius: '0.375rem',
            fontSize: '0.875rem',
            fontWeight: '500',
            transition: 'all 0.2s ease',
            color: '#CBD5E1',
            textAlign: 'center',
            whiteSpace: 'nowrap',
            letterSpacing: '-0.01em',
          },
          '.nav-link:hover': {
            background: 'rgba(56, 189, 248, 0.1)',
            color: '#E2E8F0',
            transform: 'translateY(-1px)',
          },
          '.nav-link.active': {
            color: '#38BDF8',
            background: 'rgba(56, 189, 248, 0.15)',
            fontWeight: '600',
          },
          '.nav-link.active::after': {
            content: "''",
            position: 'absolute',
            bottom: '-1px',
            left: '50%',
            transform: 'translateX(-50%)',
            width: '24px',
            height: '2px',
            background: 'linear-gradient(to right, #38BDF8, #A855F7)',
            borderRadius: '1px',
          },
          '.nav-button': {
            background: 'linear-gradient(135deg, rgba(96, 165, 250, 0.2) 0%, rgba(168, 85, 247, 0.2) 100%)',
            border: '1px solid rgba(168, 85, 247, 0.3)',
            color: '#E2E8F0',
            padding: '0.5rem 1.25rem',
            borderRadius: '0.375rem',
            fontSize: '0.875rem',
            fontWeight: '600',
            letterSpacing: '0.01em',
            transition: 'all 0.2s ease',
            display: 'inline-flex',
            alignItems: 'center',
            justifyContent: 'center',
            cursor: 'pointer',
            position: 'relative',
            overflow: 'hidden',
            zIndex: '1',
            textAlign: 'center',
            boxShadow: '0 2px 8px rgba(0, 0, 0, 0.1)',
          },
          '.nav-button:hover': {
            background: 'linear-gradient(135deg, rgba(96, 165, 250, 0.3) 0%, rgba(168, 85, 247, 0.3) 100%)',
            borderColor: 'rgba(168, 85, 247, 0.5)',
            color: '#F3F4F6',
            transform: 'translateY(-1px)',
            boxShadow: '0 4px 12px rgba(168, 85, 247, 0.2)',
          },
          '.nav-button:active': {
            transform: 'translateY(0)',
            boxShadow: '0 2px 6px rgba(168, 85, 247, 0.15)',
          },
          '.features-grid': {
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
            gap: '1.5rem',
            width: '100%',
            maxWidth: '1200px',
            margin: '0 auto',
          },
          '.steps-grid': {
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
            gap: '1.5rem',
            width: '100%',
            maxWidth: '1200px',
            margin: '0 auto',
          },
          'textAlign': {
            'center': 'center',
            'left': 'left',
            'right': 'right',
            'justify': 'justify',
          },
          'maxWidth': {
            '8xl': '88rem',
            '9xl': '96rem',
          },
          'gridTemplateColumns': {
            'auto-fit': 'repeat(auto-fit, minmax(280px, 1fr))',
            'auto-fill': 'repeat(auto-fill, minmax(280px, 1fr))',
          },
          'gap': {
            '14': '3.5rem',
            '16': '4rem',
            '20': '5rem',
          },
          'padding': {
            '18': '4.5rem',
            '22': '5.5rem',
          },
          'margin': {
            '18': '4.5rem',
            '22': '5.5rem',
          },
          '.text-balance': {
            'text-wrap': 'balance',
          },
          '.text-pretty': {
            'text-wrap': 'pretty',
          },
          '.overflow-ellipsis': {
            'text-overflow': 'ellipsis',
            'white-space': 'nowrap',
            'overflow': 'hidden',
          },
          '.line-clamp-2': {
            'display': '-webkit-box',
            '-webkit-line-clamp': '2',
            '-webkit-box-orient': 'vertical',
            'overflow': 'hidden',
          },
          '.line-clamp-3': {
            'display': '-webkit-box',
            '-webkit-line-clamp': '3',
            '-webkit-box-orient': 'vertical',
            'overflow': 'hidden',
          },
          '.line-clamp-4': {
            'display': '-webkit-box',
            '-webkit-line-clamp': '4',
            '-webkit-box-orient': 'vertical',
            'overflow': 'hidden',
          },
        },
      },
    },
    plugins: [],
    safelist: [
      'from-primary-400',
      'to-primary-600',
      'from-accent-300',
      'to-accent-500',
      'hover:from-primary-300',
      'hover:to-primary-500',
      'bg-primary-500/10',
      'bg-accent-500/10',
      'from-primary-500/20',
      'via-accent-400/20',
      'to-primary-400/20',
      'w-3',
      'w-4',
      'h-3',
      'h-4',
      'w-5',
      'h-5',
      'w-6',
      'h-6',
      'mr-1.5',
      'mr-2',
      'text-xs',
      'mt-2',
      'text-emerald-400',
      'text-rose-400',
      'text-blue-400',
      'bg-emerald-400',
      'bg-rose-400',
      'bg-blue-400',
      'md:grid-cols-3',
      'space-y-2',
      'space-y-6',
      'gap-6',
      'gap-2',
      'flex-shrink-0',
      'rounded-full',
      'items-start',
      'text-green-500',
      'text-red-500',
      'text-primary-400',
      'w-1.5',
      'h-1.5',
      'mt-1.5',
      'bg-current',
      'text-green-400',
      'text-green-500',
      'text-red-400',
      'text-red-500',
      'text-blue-500',
      'text-slate-300',
      'text-slate-400',
      'bg-slate-900',
      'space-y-8',
      'mb-6',
      'p-6',
      'grid',
      'flex',
      'justify-between',
      'text-lg',
      'text-xl',
      'text-4xl',
      'font-medium',
      'font-bold',
      'gradient-text',
      'hover:shadow-glow',
      'relative',
      'z-10',
      'stroke-primary-400',
      'stroke-current',
      'fill-none',
      'animate-progress-pulse',
      'backdrop-blur-md',
      'max-w-md',
      'mx-auto',
      'space-y-4',
      'space-y-3',
      'text-3xl',
      'text-sm',
      'font-bold',
      'text-slate-200',
      'text-center',
      'min-h-screen',
      'flex-col',
      'items-center',
      'justify-center',
      'p-6',
      'from-primary-400',
      'to-accent-400',
      'hover:from-primary-500',
      'hover:to-accent-500',
      'shadow-primary-400/10',
      'hover:shadow-primary-400/20',
      'tracking-wide',
      'leading-relaxed',
      'opacity-75',
      'font-semibold',
      'space-x-2',
      'h-8',
      'h-5',
      'w-5',
      'h-2.5',
      'w-2.5',
      'gap-[2px]',
      'text-[10px]',
      'px-1.5',
      'py-0.5',
      'py-1',
      'rounded-sm',
      'max-h-32',
      'opacity-0',
      'opacity-100',
      'duration-150',
      'ease-in-out',
      'gap-1.5',
      'px-3',
      'backdrop-blur',
      'bg-slate-900/90',
      'border-slate-700/50',
      'hover:bg-slate-800/50',
      'bg-primary-400/10',
      'fixed',
      'top-0',
      'left-0',
      'right-0',
      'z-50',
      'h-8',
      'border-b',
      'max-w-7xl',
      'mx-auto',
      'px-3',
      'py-0.5',
      'flex',
      'items-center',
      'justify-between',
      'text-[10px]',
      'font-semibold',
      'w-5',
      'h-5',
      'flex-col',
      'gap-[2px]',
      'p-1',
      'rounded-sm',
      'hover:bg-slate-800/50',
      'w-2.5',
      'h-0.5',
      'bg-slate-400',
      'absolute',
      'top-8',
      'transition-all',
      'overflow-hidden',
      'opacity-75',
      'mb-0.5',
      'bg-slate-900/90',
      'backdrop-blur',
      'border-slate-700/50',
      'text-accent-400',
      'text-accent-500',
      'bg-accent-400',
      'bg-accent-500',
      'border-accent-400',
      'border-accent-500',
      'focus:border-accent-500',
      'focus:ring-accent-500',
      'focus:ring-opacity-50',
      'shadow-accent-400/10',
      'hover:shadow-accent-400/20',
      'hover:border-accent-400/30',
      'bg-accent-400/10',
      'bg-purple-500/5',
      'backdrop-blur-lg',
      'rounded-lg',
      'font-semibold',
      'text-slate-200',
      'text-slate-300',
      'text-slate-400',
      'p-4',
      'p-6',
      'p-8',
      'space-y-4',
      'space-y-6',
      'space-y-8',
      'text-center',
      'text-lg',
      'text-xl',
      'text-2xl',
      'text-4xl',
      'max-w-2xl',
      'max-w-4xl',
      'mx-auto',
      'items-center',
      'justify-between',
      'justify-end',
      'flex-shrink-0',
      'min-h-screen',
      'relative',
      'fixed',
      'absolute',
      'inset-0',
      'z-10',
      'z-50',
      'overflow-hidden',
      'w-4',
      'h-4',
      'ml-2',
      'text-sm',
      'inline-flex',
      'items-center',
      'hidden',
      'cursor-pointer',
      'text-emerald-400',
      'gap-2',
      'mt-3',
      'flex',
      'items-center',
      'document-header',
      'text-center',
      'flex',
      'flex-col',
      'items-center',
      'justify-center',
      'mb-2',
      'mb-4',
      'mb-6',
      'md:text-2xl',
      'mb-8',
      'info-icon-container',
      'info-icon',
      'info-tooltip',
      'info-tooltip-list',
      'key',
      'w-5',
      'h-5',
      'w-4',
      'h-4',
      'ml-1',
      'ml-2',
      'ml-4',
      'gap-2',
      'cursor-help',
      'transition-all',
      'duration-200',
      'ease-in-out',
      'transform',
      'scale-110',
      'opacity-0',
      'opacity-100',
      'visible',
      'invisible',
      'z-50',
      'backdrop-blur-md',
      'bg-slate-900/95',
      'border',
      'border-purple-500/30',
      'shadow-lg',
      'shadow-black/20',
      'rounded-lg',
      'p-4',
      'whitespace-nowrap',
      'font-mono',
      'text-sm',
      'text-slate-300',
      'hover:text-purple-400',
      'flex',
      'items-center',
      'justify-center',
      'bg-slate-800/30',
      'rounded-xl',
      'p-5',
      'border-slate-700/50',
      'space-y-2.5',
      'space-y-4',
      'gap-8',
      'w-2',
      'h-2',
      'bg-rose-400/20',
      'text-2xl',
      'md:p-8',
      'font-mono',
      'tracking-wider',
      'uppercase',
      'nav-blur',
      'nav-link',
      'gradient-button',
      'feature-card',
      'feature-icon',
      'step-card',
      'step-number',
      'about-image-placeholder',
      'backdrop-blur-sm',
      'feature-card',
      'step-card',
      'hero-gradient',
      'hero-text',
      'icon-container',
      'step-number',
      'from-primary-400/10',
      'to-accent-400/10',
      'via-accent-400/5',
      'hover:shadow-accent-400/10',
      'hover:shadow-accent-400/20',
      'hover:-translate-y-1',
      'hover:-translate-y-2',
      'hover:scale-105',
      'transition-transform',
      'duration-300',
      'text-tiny',
      'text-xs',
      'text-sm',
      'text-base',
      'text-lg',
      'text-xl',
      'text-2xl',
      'text-3xl',
      'text-4xl',
      'text-5xl',
      'text-6xl',
      'text-hero',
      'tracking-tighter',
      'tracking-tight',
      'tracking-normal',
      'tracking-wide',
      'tracking-wider',
      'tracking-widest',
      'tracking-tech',
      'leading-tighter',
      'leading-tight',
      'leading-snug',
      'leading-normal',
      'leading-relaxed',
      'leading-loose',
      'leading-hero',
      'font-sans',
      'font-mono',
      'font-display',
      'font-tech',
      'social-links',
      'footer-bottom',
      'h-5',
      'w-5',
      'h-4',
      'w-4',
      'text-xs',
      'text-sm',
      'text-slate-400',
      'text-slate-500',
      'hover:text-accent-300',
      'transition-colors',
      'gap-4',
      'gap-6',
      'gap-8',
      'gap-12',
      'grid-cols-1',
      'md:grid-cols-2',
      'lg:grid-cols-4',
      'col-span-1',
      'md:col-span-2',
      'lg:col-span-1',
      'about-benefits-list',
      'checkmark-icon',
      'benefit-text',
      'w-3.5',
      'h-3.5',
      'text-emerald-400',
      'bg-slate-800/30',
      'border-slate-700',
      'border-slate-700/50',
      'text-slate-300',
      'text-slate-400',
      'text-accent-300',
      'font-light',
      'font-extrabold',
      'tracking-tighter',
      'tracking-tight',
      'tracking-wide',
      'tracking-widest',
      'tracking-tech',
      'leading-relaxed',
      'leading-hero',
      'text-hero',
      'text-xs',
      'text-sm',
      'text-base',
      'text-lg',
      'text-xl',
      'text-2xl',
      'text-3xl',
      'text-4xl',
      'font-mono',
      'font-display',
      'gap-8',
      'gap-12',
      'py-16',
      'py-20',
      'pt-16',
      'pb-20',
      'mb-12',
      'mb-10',
      'mb-6',
      'mb-4',
      'mb-3',
      'mb-2',
      'px-4',
      'sm:px-6',
      'lg:px-8',
      'md:p-12',
      'p-8',
      'p-6',
      'rounded-xl',
      'rounded-2xl',
      'md:grid-cols-2',
      'md:grid-cols-3',
      'md:grid-cols-4',
      'lg:grid-cols-4',
      'max-w-2xl',
      'max-w-3xl',
      'max-w-7xl',
      'aspect-video',
      'bg-accent-400/10',
      'bg-primary-400/10',
      'bg-accent-400/20',
      'bg-slate-800/20',
      'text-[10px]',
      'text-[11px]',
      'w-8',
      'h-8',
      'w-3',
      'h-3',
      'text-emerald-400',
      'about-benefits-list',
      'checkmark-icon',
      'benefit-text',
      'nav-link',
      'step-card',
      'step-number',
      'feature-card',
      'icon-container',
      'hero-gradient',
      'hero-text',
      'about-image-container',
      'footer-bottom',
      'social-links',
      'from-slate-900',
      'via-[#1a1f35]',
      'to-slate-900',
      'from-accent-400/10',
      'to-primary-400/10',
      'from-primary-400/5',
      'via-primary-400/5',
      'to-primary-400/20',
      'line-clamp-5',
      'text-accent-200',
      'underline',
      'text-emerald-400',
      'text-slate-500',
      'ml-2',
      'inline-flex',
      'gap-2',
      'text-xs',
      'features-grid',
      'steps-grid',
      'max-w-7xl',
      'mx-auto',
      'px-4',
      'sm:px-6',
      'lg:px-8',
      'py-12',
      'py-16',
      'py-20',
      'text-center',
      'mb-8',
      'mb-12',
      'mb-16',
      'text-2xl',
      'text-3xl',
      'text-4xl',
      'font-bold',
      'gradient-text',
      'text-slate-300',
      'max-w-2xl',
      'mx-auto',
      'flex',
      'flex-col',
      'sm:flex-row',
      'justify-center',
      'gap-4',
      'gap-6',
      'gap-8',
      'text-lg',
      'px-6',
      'py-3',
      'bg-opacity-20',
      'backdrop-blur-sm',
      'rounded-2xl',
      'p-6',
      'md:p-8',
      'border',
      'border-slate-700/50',
      'bg-slate-900/50',
      'grid',
      'grid-cols-1',
      'md:grid-cols-2',
      'lg:grid-cols-3',
      'gap-6',
      'gap-8',
      'gap-12',
      'py-8',
      'px-4',
      'sm:px-6',
      'lg:px-8',
      'border-t',
      'border-slate-700/50',
      'grid-cols-1',
      'md:grid-cols-4',
      'gap-8',
      'mt-8',
      'pt-6',
      'border-t',
      'flex',
      'flex-wrap',
      'justify-between',
      'items-center',
      'gap-4',
      'text-sm',
      'text-slate-500',
      'links',
      'mt-4',
      'text-slate-500',
      'hover:text-accent-300',
      'transition-colors',
      'mr-4',
    ]
  }